// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrivacyAnalytics.Infrastructure.Data;

#nullable disable

namespace PrivacyAnalytics.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260718072230_AddPublicWriteKeyAndAnalyticsEventForeignKey")]
    partial class AddPublicWriteKeyAndAnalyticsEventForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrivacyAnalytics.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("AnonymousDailyHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("anonymous_daily_hash");

                    b.Property<string>("DurableHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("durable_hash");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authenticated");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("path");

                    b.HasKey("EventId", "Timestamp");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_analytics_events_organization_id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_analytics_events_timestamp_desc");

                    b.ToTable("analytics_events", (string)null);
                });

            modelBuilder.Entity("PrivacyAnalytics.Domain.Entities.ErasureAuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("PurgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at_utc");

                    b.Property<string>("PurgedIdentifierHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("purged_identifier_hash");

                    b.Property<int>("RecordsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("records_affected");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("requested_by");

                    b.HasKey("AuditId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_erasure_audit_log_organization_id");

                    b.ToTable("erasure_audit_log", (string)null);
                });

            modelBuilder.Entity("PrivacyAnalytics.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicWriteKey")
                        .HasColumnType("uuid")
                        .HasColumnName("public_write_key");

                    b.HasKey("Id");

                    b.HasIndex("PublicWriteKey")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("PrivacyAnalytics.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.HasOne("PrivacyAnalytics.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analytics_events_organization_id");
                });
#pragma warning restore 612, 618
        }
    }
}
